import { randomInSphere, randomVector } from "./tools.js";

const size = 100000;

const entities = [{
    model: "skybox",
    scale: Array(3).fill(size),
    // orientation: randomQuat(),
    mass: 0.1
}, {
    scale: Array(3).fill(0.1),
    mass: 10,
    camera: {
        near: 0.1,
        far: size * 2,
        fov: 60
    }
}];

// I should specify a camera separately
// so it can become a named uniform buffer
// switching the camera should be done with a script
// camera can have an entity id to get position and orientation

let config = {
    size, 
    autoGenerate: [
        {
            length: 1000,
            conf: { size: { min: 100, max: 1000 } },
            f: (conf) => {
                const s = conf.size.min + Math.random() * (conf.size.max - conf.size.min);
                const mass = s * 100000000;
                const position = randomInSphere(size - s * 2);

                return {
                    model: "asteroid",
                    position,
                    velocity: randomVector(-10, 10),
                    torque: randomVector(-10 * mass, 10 * mass),
                    mass,
                    scale: Array(3).fill(s)
                }
            }
        },
        {
            length: 100000,
            conf: {
                size: {
                    min: 1,
                    max: 200
                }
            },
            f: (conf) => { 
                const s = conf.size.min + Math.random() * (conf.size.max - conf.size.min);
                return {
                    model: "crate",
                    position: randomInSphere(size),
                    velocity: randomVector(-10, 10),
                    angularVelocity: randomVector(-1, 1),
                    mass: 10000,
                    scale: Array(3).fill(s)
                }            
            }
        }
    ],
    models: ["skybox", "crate", "asteroid"],
    uniforms: {
        size: {
            type: 'f32',
            value: [size]
        },
        gravityConfig: {
            type: 'f32',
            value: [
            10,          // G
            1,           // minDistance
            size / 50,   // maxDistance
            0            // pad
        ]},
        phongLight: {
            type: 'f32',
            value: [
            ...[Math.PI, Math.PI, Math.PI],//...randomDirection(),       // direction
            0,                          // pad
            0.9 + 0.1 * Math.random(),  // R
            0.9 + 0.1 * Math.random(),  // G
            0.9 + 0.1 * Math.random(),  // B
            0                           // pad
        ]},
        activeCamera: {
            type: 'u32',
            value: [1]
        }
    },
    entities,
    layers: [
        {
            label: "physics",
            systems: ["gravity", "localForce", "force", "torque", "movement", "rotation"]
        },
        {
            label: "transformations",
            systems: ["transform", "camera"]
        }
    ]
}

function prepareEntities(config) {
    const { entities, autoGenerate, ...rest } = config;
    const autoGenerated = autoGenerate.map(thing => {
        return Array.from(thing, () => thing.f(thing.conf));
    }).flat();
    return { entities: [...entities, ...autoGenerated], ...rest}
}

config = prepareEntities(config);

Deno.writeTextFile("./data/scenes/space.json", JSON.stringify(config, {}, 2));