performance.mark('space-scene-module');

import { Scene } from "../Engine/scene.js";

performance.mark('space-scene-assets-loaded');
performance.measure('space-scene-assets', 'space-scene-module', 'space-scene-assets-loaded');

export class SpaceScene extends Scene {

    constructor(device, canvas, myConfig) {
        performance.mark('start-space-scene');

        // perform any custom work related to the space scene specifically
        const { entities, autoGenerate, ...rest } = myConfig;
        const autoGenerated = autoGenerate.map(thing => {
            return Array.from(thing, () => thing.f(thing.conf));
        }).flat();
        const config = { entities: [...entities, ...autoGenerated], ...rest}

        super(device, canvas, config);

        performance.mark('space-scene-configured');
        performance.measure('space-scene-initialisation', 'start-space-scene', 'space-scene-configured');
    }

}
