import { cameraScript } from "../../scripts/camera.js";
import { loadComponent } from "../components.js";
import { loadModel } from "../model.js";
import { loadSystem } from "../system.js";
import { CommandQueue } from "./CommandQueue.js";
import { EntityFramework } from "./ECS/Framework.js";
import { GPUBufferManager } from "./GPUBuffers.js";
import { Layer } from "./Layer.js";
import { ResourceRegistry } from "./ResourceRegistry.js";
import { ComputeSystem } from "./systems/compute.js";
import { Renderer } from "./systems/renderer.js";
import { ScriptingSystem } from "./systems/scripts.js";

const SUPPORTED_TYPES = {
    'f32': Float32Array,
    'u32': Uint32Array
}

export class Scene {

    static prepareEntities(config) {
        const { entities, autoGenerate, ...rest } = config;
        const autoGenerated = autoGenerate.map(thing => {
            return Array.from(thing, () => thing.f(thing.conf));
        }).flat();
        return { entities: [...entities, ...autoGenerated], ...rest}
    }

    // All async work needs to be done before we call the constructor
    static async create(device, canvas, config) {
        performance.mark('scene-create-0');

        // const config = Scene.prepareEntities(myConfig);

        // Load systems (WGSL modules)
        for (const layer of config.layers) {
            layer.systems = await Promise.all(layer.systems.map(loadSystem));
        }

        // Work out necessary components from layers
        const requiredBuffers = new Set(config.layers.map(l => {
            return l.systems.map(s => {
                return s.groups.flat()
            }).flat();
        }).flat())
        const providedUniforms = new Set(["deltaTime", "canvas", ...Object.keys(config.uniforms)]);
        const requiredComponents = Array.from(requiredBuffers.difference(providedUniforms));
        
        // load component definitions and add to config
        config.components = Object.fromEntries(
            await Promise.all(requiredComponents.map(async (c) => [c, await loadComponent(c)]))
        );

        // Extract models from entities
        const models = Array.from(new Set(
            [...config.entities.filter(e => e.model).map(e => e.model), ...config.models]
        ));
                
        // Load models (meshes and materials, including WGSL modules)
        config.models = Object.fromEntries(await Promise.all(models.map(async (m) => [m, await loadModel(m)])));



        performance.mark('scene-create-1');
        performance.measure("shaders loaded", "scene-create-0", "scene-create-1");
        return new this(device, canvas, config);
    }
    

    // instances get nicely prepared data
    constructor(device, canvas, config) { 
        performance.mark('scene start');
        
        // put some basic things in place
        this.device = device;
        this.canvas = canvas;
        this.layers = new Map();
        this.commands = new CommandQueue();
        this.buffers = new GPUBufferManager(device);
        this.input = new ResourceRegistry();
        this.models = new ResourceRegistry();
        this.initMouse();
        this.initKeys();
        
        const {
            models,
            layers,
            uniforms,
            components,
            entities: originalEntities
        } = config;

        

        this.__createModels(models);
        
        // Component handling
        // This is dodgy

        // set default values from component defaults?
        const entities = originalEntities.map(e => ({...components, ...e}))

        // the model is provided as a string - we replace it with an integer for indexing
        components.model = 0;

        // we query the world for scriptables at the moment
        // Since it happens on the CPU anyway
        components.scriptable = [0, 0];

        
        // Initialise the world
        const maxEntities = entities.length;
        this.world = new EntityFramework({
            components,
            maxEntities
        });

        // register entities
        entities.forEach(entity => { 
            // convert the model to an index as necessary
            if (entity.model) {
                entity.model = this.models.indexOf(entity.model);
            }
            const entityId = this.createEntity(entity);
        
            // Hack to add the script to the camera based on provided cameraId uniform
            if (uniforms.activeCamera.value[0] == entityId) {
                this.world.addComponent(entityId, "scriptable", [0, 0]);
            }
        })
        
        this.buffers.createFromWorld(this.world);
        this.buffers.indexBy(this.world, "model", 0);
        this.__createUniformBuffers(uniforms);
        
        
        // set up scripts
        const scripts = [cameraScript]
        const scriptData = [{
            torque: [-0.25, -0.25, -2],
            thrust: -1500,
            brake: -1000
        }]

        this.scripts = new ScriptingSystem(scripts, scriptData);

        // can't initialise systems until the buffers are set up
        this.addLayers(layers);
        this.renderer = new Renderer({
            buffers: this.buffers,
            device: this.device,
            canvas: this.canvas,
            models: this.models
        });

        performance.mark('scene end');
        performance.measure('scene init', 'scene start', 'scene end');
    }

    __createUniformBuffers(uniforms) { 
        
        this.buffers.createUniform({
            label: "deltaTime",
            data: new Float32Array([0])
        });

        this.buffers.createUniform({
            label: "canvas",
            data: new Float32Array([1])
        });
        
        for (const [label, { type, value }] of Object.entries(uniforms)) {
            if (!Object.keys(SUPPORTED_TYPES).includes(type)) throw new Error(`unsuported type '${type}'`);
            const data = new SUPPORTED_TYPES[type](value);
            this.buffers.createUniform({label, data});
        }
    }

    addSystem(system) {
        this.layers.push(new Layer([system]));        
    }
    addLayer(name, systems) {
        this.layers.set(name, new Layer(systems));
    }

    addLayers(layers) {
        for (const layer of layers) {
            const systems = layer.systems.map((layer) => { 
                return new ComputeSystem(layer, {
                    buffers: this.buffers,
                    device: this.device
                });
            })
            this.addLayer(layer.label, systems);
        }
    }

    __createModels(models) { 
        for (const key in models) {
            const { mesh, material } = models[key];
            const { buffer, length } = this.buffers.createVertex({
                label: `${key} vertices (stride: ${mesh.stride})`, ...mesh
            });
            this.models.set(key, {
                vertexBuffer: buffer,
                vertexCount: length,
                material
            });        
        }
    }

    createEntity(components) {
        const id = this.world.createEntity();
        for (const [key, value] of Object.entries(components)) {
            const k = `${key[0].toLowerCase()}${key.slice(1)}`;
            this.world.addComponent(id, k, value);
        }
        return id;
    }


    resize(canvas) {
        canvas.width = document.body.clientWidth;
        canvas.height = document.body.clientHeight;
        this.buffers.setUniform("canvas", new Float32Array([canvas.width / canvas.height]));
        for (const layer of this.layers.values()) {
            layer.resize(canvas);            
        }

        // wait, this needs to be created by the spaceScene!
        this.renderer.resize(canvas);
    }

    initMouse() { 
        this.input.set("mouse", { movementX: 0, movementY: 0 });
        const mouse = this.input.get("mouse");
        function updateMouse(ev) { 
            mouse.movementX = ev.movementX;
            mouse.movementY = ev.movementY;
        }
        this.canvas.addEventListener("click", () => {
            if (document.pointerLockElement !== this.canvas && this.canvas.requestPointerLock) {
                this.canvas.requestPointerLock();
            }
        });
        document.addEventListener("pointerlockchange", () => {
            if (document.pointerLockElement === this.canvas) {
                this.canvas.addEventListener("mousemove", updateMouse);
            } else {
                this.canvas.removeEventListener("mousemove", updateMouse);
            }
        });
    }

    initKeys() { 
        const keyMap = "wasd";
        this.input.set("keys", Object.fromEntries(Array.from(keyMap).map(k => [k, false])));
        const keys = this.input.get("keys");
        globalThis.addEventListener("keydown", ev => {
            keys[ev.key] = true;
        });
        globalThis.addEventListener("keyup", ev => {
            keys[ev.key] = false;
        });
    }

    get ctx() {
        return {
            buffers: this.buffers,
            world: this.world,
            renderables: this.models,
            input: this.input,
            activeEntities: this.world.getActive(),
            commands: this.commands,
            canvas: this.canvas,
            device: this.device
        }
    }

    update() {

        performance.mark(`${this.constructor.name} start`);
        const ctx = this.ctx;
        this.scripts.update(ctx);
        this.commands.flush(ctx);
        for (const layer of this.layers.values()) {
            layer.update(ctx);
        }
        this.renderer.update(ctx);
        performance.mark(`${this.constructor.name} complete`);
        performance.measure(`${this.constructor.name} update`, `${this.constructor.name} start`, `${this.constructor.name} complete`);
    }

    animate() { 
        requestAnimationFrame(this.frame.bind(this));
    }

    frame(ts) {
        const deltaTime = (ts - this.prevTime || 1000 / 60) / 1000;
        this.prevTime = ts;
        this.buffers.setUniform("deltaTime", new Float32Array([deltaTime]));
        this.update();
        requestAnimationFrame(this.frame.bind(this));
    }

}